include: [./external/franka_ros2/docker-compose.yml]
services:

  franka_ros2:
    build:
      args:
        - USER_UID=1001
        - USER_GID=1001
    image: "franka_ros2:latest"
    init: true
    network_mode: host
    entrypoint: ""
    command: >
      ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=true

  franka_teleop:
    extends:
      service: base
    image: "franka_teleop:latest"
    volumes:
      - ./handcv/:/ros2_ws/src/handcv/
      - ./hand_interfaces/:/ros2_ws/src/hand_interfaces/
      - ./franka_teleop/:/ros2_ws/src/franka_teleop/
      - ./franka_teleop_bringup/:/ros2_ws/src/franka_teleop_bringup/
      - ./cv_franka_bridge/:/ros2_ws/src/cv_franka_bridge/
    command: >
      bash -c "
      source /opt/ros/jazzy/setup.bash &&
      colcon build &&
      source install/setup.bash &&
      ros2 launch franka_teleop_bringup bringup.launch.py
      "

  handcv:
    extends:
      service: base
    image: "handcv:latest"
    volumes:
      - ./handcv/:/ros2_ws/src/handcv/
      - ./hand_interfaces/:/ros2_ws/src/hand_interfaces/
    command: >
      bash -c "
      source /opt/ros/jazzy/setup.bash &&
      colcon build --packages-select handcv &&
      source install/setup.bash &&
      ros2 launch handcv camera.launch.py
      "

  rviz:
    extends:
      service: base
    image: "rviz:latest"
    command: ros2 run rviz2 rviz2

  calibration:
    extends:
      service: realsense
    image: "calibration:latest"
    command: >
      ros2 run camera_calibration cameracalibrator
      --no-service-check
      --pattern charuco
      --size 5x7
      --square 0.0320
      --charuco_marker_size 0.0246
      --aruco_dict 6x6_250
      --ros-args
      --remap image:=/camera/infra1/image_rect_raw
      --remap camera:=/camera/infra1

  realsense:
    build: 
      context: .
      dockerfile: camera.Dockerfile
      args:
        - USER_UID=1001
        - USER_GID=1001
        - USERNAME=${USERNAME}
    image: "realsense:latest"
    network_mode: host
    # ipc: host
    privileged: true
    tty: true
    stdin_open: true
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./advanced.json:/config/advanced.json:ro
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command: > 
      ros2 launch realsense2_camera rs_launch.py 
      camera_name:=camera
      camera_namespace:=/
      enable_color:=false
      enable_depth:=false
      enable_infra1:=true
      json_file_path:=/config/advanced.json

  base:
    build: 
      context: .
      dockerfile: teleop.Dockerfile
      args:
        - USER_UID=1001
        - USER_GID=1001
        - USERNAME=${USERNAME}
    network_mode: host
    privileged: true
    tty: true
    init: true
    stdin_open: true
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ros2 run demo_nodes_cpp talker
