"""
Find the 3D pose of a human hand using computer vision.

Not using cv_bridge, take messages from the /image_raw topic and convert them
into OpenCV images for mediapipe to use to figure out where a user's hand
is located. Afterwards, figure out the 3D locations of the hand's joints
generated by mediapipe using the depth_image_proc package.

SUBSCRIBERS:
  + /camera/color/image_raw (Image) - Raw image data from the RealSense D435i
  camera.
  + /camera/aligned_depth_to_color/image_raw (Image) - Aligned depth image from
  the RealSense D435i camera.
PUBLISHERS:
  + /cv_image (Image) - Annotated image with the 3D location of the hand's
  pose.
  + /waypoint (PointStamped) - The 3D location of the hand's pose.
  + /right_gesture (String) - The gesture that the right hand is making.

"""

from typing import Any, NamedTuple

import cv2
import mediapipe as mp
import message_filters
import numpy as np
import rclpy
from geometry_msgs.msg import PointStamped
from mediapipe.tasks.python.vision.gesture_recognizer import GestureRecognizerResult
from rclpy.node import Node
from sensor_msgs.msg import Image
from std_msgs.msg import String

from .mediapipehelper import MediaPipeRos as mps


class ProcessedColorImage(NamedTuple):
    annoted_image: np.ndarray
    gesture_result: Any


class HandCV(Node):
    def __init__(self):
        super().__init__("handcv")

        self.declare_parameter("camera_name")
        camera_name = (
            self.get_parameter("camera_name").get_parameter_value().string_value
        )

        self.mps = mps()

        # create message_filter subscribers
        color_sub = message_filters.Subscriber(
            self, Image, f"{camera_name}/color/image_raw"
        )
        depth_sub = message_filters.Subscriber(
            self, Image, f"{camera_name}/depth/image_rect_raw"
        )

        ts = message_filters.ApproximateTimeSynchronizer(
            [color_sub, depth_sub],
            queue_size=10,
            slop=0.1,  # 100ms tolerance
        )
        ts.registerCallback(self.sync_callback)

        # create publishers
        self.cv_image_pub = self.create_publisher(Image, "cv_image", 10)
        self.waypoint_pub = self.create_publisher(PointStamped, "waypoint", 10)
        self.right_gesture_pub = self.create_publisher(String, "right_gesture", 10)

    def process_depth_image(
        self,
        depth_image: np.ndarray,
        annotated_image: np.ndarray,
        gesture_result: GestureRecognizerResult,
    ) -> tuple[Image, PointStamped, str]:
        """
        Process the depth image to find the 3D location of the hand's pose.

        Args:
        ----
        annotated_image (np.array): The annotated image with the 3D location of
        the hand's pose.
        gesture (str): The result of the hand landmark detection.

        Returns:
        -------
        cv_image (Image): The annotated image with the 3D location of the hand's
        pose.
        right_gesture (String): The gesture that the right hand is making.

        """
        right_gesture = "None"
        right_index = None
        self.get_logger().info(f"gesture_result: {gesture_result}")
        if gesture_result.gestures and gesture_result.handedness:
            for hand in gesture_result.handedness:
                if hand[0].category_name == "Right":
                    right_gesture = gesture_result.gestures[0][0].category_name
                    right_index = 0

        self.get_logger().info(f"right_gesture: {right_gesture}")
        img_w = annotated_image.shape[1]
        img_h = annotated_image.shape[0]
        if gesture_result.hand_landmarks and right_index is not None:
            self.get_logger().info("Right Hand")
            coords = np.array(
                [
                    [
                        landmark.x * img_w,
                        landmark.y * img_h,
                    ]
                    for landmark in [
                        gesture_result.hand_landmarks[right_index][0],
                        gesture_result.hand_landmarks[right_index][1],
                        gesture_result.hand_landmarks[right_index][2],
                        gesture_result.hand_landmarks[right_index][5],
                        gesture_result.hand_landmarks[right_index][9],
                        gesture_result.hand_landmarks[right_index][14],
                        gesture_result.hand_landmarks[right_index][17],
                    ]
                ]
            )
            # now perform the math on the numpy arrays. I think this is faster?
            length = coords.shape[0]
            sum_x = np.sum(coords[:, 0])
            sum_y = np.sum(coords[:, 1])
            centroid = np.array([sum_x / length, sum_y / length, 0.0])

        try:
            centroid[2] = depth_image[int(centroid[1]), int(centroid[0])]
        except Exception:
            centroid = np.array([0.0, 0.0, 0.0])

        waypoint = PointStamped()
        waypoint.point.x = centroid[0]
        waypoint.point.y = centroid[1]
        waypoint.point.z = centroid[2]

        text = f"(x: {np.round(centroid[0] - img_w / 2)}, y: {np.round(centroid[1] - img_h / 2)}, z: {np.round(centroid[2])})"

        annotated_image = cv2.putText(
            annotated_image,
            text,
            (int(centroid[0]) - 100, int(centroid[1]) + 40),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (255, 255, 255),
            1,
        )

        annotated_image = cv2.circle(
            annotated_image,
            (int(centroid[0]), int(centroid[1])),
            10,
            (255, 255, 255),
            -1,
        )

        cv_image = self.rgb8_to_ros_image(annotated_image)

        return cv_image, waypoint, right_gesture

    def process_color_image(self, color_img) -> ProcessedColorImage:
        """Process the color image to find the 3D location of the hand's pose."""
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=color_img)

        gesture_result = self.mps.gesture_recognizer.recognize(mp_image)

        annotated_image = self.mps.draw_landmarks_on_image(
            rgb_image=self.color_image,
            detection_result=gesture_result,
            logger=self.get_logger(),
        )

        return ProcessedColorImage(annotated_image, gesture_result)

    def ros_image_to_color(self, msg: Image) -> np.ndarray:
        # Didn't want to have dependency on cv_bridge, old numpy
        # beautiful!
        img = np.frombuffer(msg.data, dtype=np.uint8).reshape(msg.height, msg.width, -1)
        if msg.encoding == "mono8":  # n eeds
            _msg = "needs to be bgr8 or rgb8"
            raise ValueError(_msg)
        if msg.encoding == "bgr8":
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        return img

    def ros_image_to_gray(self, msg: Image) -> np.ndarray:
        # Didn't want to have dependency on cv_bridge, old numpy
        # beautiful!
        img = np.frombuffer(msg.data, dtype=np.uint8).reshape(msg.height, msg.width, -1)
        self.get_logger().info(f"msg.encoding: {msg.encoding}")
        if msg.encoding == "mono8":
            return img[:, :, 0]
        if msg.encoding == "bgr8":
            return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        return cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    def ros_depth_to_array(self, msg: Image) -> np.ndarray:
        # 16UC1, millimeters
        return np.frombuffer(msg.data, dtype=np.uint16).reshape(msg.height, msg.width)

    def rgb8_to_ros_image(self, img: np.ndarray, frame_id: str = "") -> Image:
        # inverse of ros_image_to_gray, no cv_bridge dependency
        msg = Image()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = frame_id
        h, w = img.shape[:2]
        msg.height = int(h)
        msg.width = int(w)
        msg.encoding = "rgb8"
        msg.is_bigendian = 0
        msg.step = int(w) * 3
        msg.data = img.tobytes()
        return msg

    def process_image_msgs(self, color_msg, depth_msg):
        self.color_image = self.ros_image_to_color(color_msg)
        self.image_width, self.image_height = self.color_image.shape[:2]

        self.depth_image = self.ros_depth_to_array(depth_msg)

        return self.color_image, self.depth_image

    def sync_callback(self, color_msg, depth_msg):
        color_img, depth_img = self.process_image_msgs(
            color_msg=color_msg, depth_msg=depth_msg
        )
        processed_color_img = self.process_color_image(color_img=color_img)
        cv_image, waypoint, right_gesture = self.process_depth_image(
            depth_image=depth_img,
            annotated_image=processed_color_img.annoted_image,
            gesture_result=processed_color_img.gesture_result,
        )
        stamp = self.get_clock().now().to_msg()
        cv_image.header.stamp = stamp
        waypoint.header.stamp = stamp

        self.cv_image_pub.publish(cv_image)
        self.right_gesture_pub.publish(String(data=right_gesture))
        self.waypoint_pub.publish(waypoint)


def main(args=None):
    rclpy.init(args=args)

    handcv = HandCV()

    rclpy.spin(handcv)


if __name__ == "__main__":
    main()
