"""
Find the 3D pose of a human hand using computer vision.

Using cv_bridge, take messages from the /image_raw topic and convert them
into OpenCV images for mediapipe to use to figure out where a user's hand
is located. Afterwards, figure out the 3D locations of the hand's joints
generated by mediapipe using the depth_image_proc package.

SUBSCRIBERS:
  + /camera/color/image_raw (Image) - Raw image data from the RealSense D435i
  camera.
  + /camera/aligned_depth_to_color/image_raw (Image) - Aligned depth image from
  the RealSense D435i camera.
PUBLISHERS:
  + /cv_image (Image) - Annotated image with the 3D location of the hand's
  pose.
  + /waypoint (PointStamped) - The 3D location of the hand's pose.
  + /right_gesture (String) - The gesture that the right hand is making.

"""

from typing import Any, NamedTuple

import cv2 as cv
import mediapipe as mp
import message_filters
import numpy as np
import rclpy
from cv_bridge import CvBridge, CvBridgeError
from geometry_msgs.msg import PointStamped
from numpy.typing import NDArray
from rclpy.node import Node
from sensor_msgs.msg import Image
from std_msgs.msg import String

from .mediapipehelper import MediaPipeRos as mps


class ProcessedColorImage(NamedTuple):
    annoted_image: NDArray
    gesture_result: Any


class HandCV(Node):
    def __init__(self):
        super().__init__("handcv")

        # initialize CvBridge object
        self.bridge = CvBridge()

        # initialize MediaPipe Object
        self.mps = mps()

        # create message_filter subscribers
        color_sub = message_filters.Subscriber(
            self, Image, "/camera/camera/color/image_raw"
        )
        depth_sub = message_filters.Subscriber(
            self, Image, "/camera/camera/aligned_depth_to_color/image_raw"
        )

        ts = message_filters.ApproximateTimeSynchronizer(
            [color_sub, depth_sub], queue_size=10, slop=0.1  # 100ms tolerance
        )
        ts.registerCallback(self.sync_callback)

        # create publishers
        self.cv_image_pub = self.create_publisher(Image, "cv_image", 10)
        self.waypoint_pub = self.create_publisher(PointStamped, "waypoint", 10)
        self.right_gesture_pub = self.create_publisher(
            String, "right_gesture", 10
        )

    def process_depth_image(
        self,
        depth_image: NDArray,
        annotated_image: NDArray,
        gesture_result: cv.Mat,
    ) -> tuple[Image, PointStamped, str]:
        """
        Process the depth image to find the 3D location of the hand's pose.

        Args:
        ----
        annotated_image (np.array): The annotated image with the 3D location of
        the hand's pose.
        gesture (str): The result of the hand landmark detection.

        Returns:
        -------
        cv_image (Image): The annotated image with the 3D location of the hand's
        pose.
        right_gesture (String): The gesture that the right hand is making.

        """
        right_gesture = "None"
        right_index = None
        if gesture_result.gestures and gesture_result.handedness:
            for hand in gesture_result.handedness:
                if hand.category_name == "Right":
                    right_gesture = gesture_result.gestures[0][0].category_name
                    right_index = 0

        self.get_logger().info(f"right_gesture: {right_gesture}")
        img_w = annotated_image.shape[1]
        img_h = annotated_image.shape[0]
        if gesture_result.hand_landmarks and right_index is not None:
            self.get_logger().info("Right Hand")
            coords = np.array(
                [
                    [
                        landmark.x * img_w,
                        landmark.y * img_h,
                    ]
                    for landmark in [
                        gesture_result.hand_landmarks[right_index][0],
                        gesture_result.hand_landmarks[right_index][1],
                        gesture_result.hand_landmarks[right_index][2],
                        gesture_result.hand_landmarks[right_index][5],
                        gesture_result.hand_landmarks[right_index][9],
                        gesture_result.hand_landmarks[right_index][14],
                        gesture_result.hand_landmarks[right_index][17],
                    ]
                ]
            )
            # now perform the math on the numpy arrays. I think this is faster?
            length = coords.shape[0]
            sum_x = np.sum(coords[:, 0])
            sum_y = np.sum(coords[:, 1])
            centroid = np.array([sum_x / length, sum_y / length, 0.0])

        try:
            centroid[2] = depth_image[int(centroid[1]), int(centroid[0])]
        except Exception:
            centroid = np.array([0.0, 0.0, 0.0])

        waypoint = PointStamped()
        waypoint.point.x = centroid[0]
        waypoint.point.y = centroid[1]
        waypoint.point.z = centroid[2]

        text = f"(x: {np.round(centroid[0] - img_w/2)}, y: {np.round(centroid[1] - img_h/2)}, z: {np.round(centroid[2])})"

        annotated_image = cv.putText(
            annotated_image,
            text,
            (int(centroid[0]) - 100, int(centroid[1]) + 40),
            cv.FONT_HERSHEY_COMPLEX,
            0.5,
            (255, 255, 255),
            1,
        )

        annotated_image = cv.circle(
            annotated_image,
            (int(centroid[0]), int(centroid[1])),
            10,
            (255, 255, 255),
            -1,
        )

        cv_image = self.bridge.cv2_to_imgmsg(annotated_image, encoding="bgr8")

        return cv_image, waypoint, right_gesture

    def process_color_image(self, color_img) -> ProcessedColorImage:
        """Process the color image to find the 3D location of the hand's pose."""
        try:

            mp_image = mp.Image(
                image_format=mp.ImageFormat.SRGB, data=color_img
            )

            gesture_result = self.mps.gesture_recognizer.recognize(mp_image)

            annotated_image = self.mps.draw_landmarks_on_image(
                rgb_image=self.color_image,
                detection_result=gesture_result,
                logger=self.get_logger(),
            )

            return ProcessedColorImage(annotated_image, gesture_result)

        except CvBridgeError:
            self.get_logger().error(CvBridgeError)
            return ProcessedColorImage(
                np.zeros((640, 480)), cv.Mat(shape=(640, 480))
            )

    def process_image_msgs(self, color_msg, depth_msg):
        # process the color image
        self.color_image = self.bridge.imgmsg_to_cv2(
            color_msg, desired_encoding="bgr8"
        )
        self.image_width, self.image_height = self.color_image.shape[:2]

        # process the depth image
        self.depth_image = self.bridge.imgmsg_to_cv2(
            depth_msg, desired_encoding="passthrough"
        )
        # self.depth_image = cv.flip(self.depth_image, 1)

        return self.color_image, self.depth_image

    def sync_callback(self, color_msg, depth_msg):
        color_img, depth_img = self.process_image_msgs(
            color_msg=color_msg, depth_msg=depth_msg
        )
        processed_color_img = self.process_color_image(color_img=color_img)
        cv_image, waypoint, right_gesture = self.process_depth_image(
            depth_image=depth_img,
            annotated_image=processed_color_img.annoted_image,
            gesture_result=processed_color_img.gesture,
        )
        stamp = self.get_clock().now().to_msg()
        cv_image.header.stamp = stamp
        waypoint.header.stamp = stamp

        self.cv_image_pub.publish(cv_image)
        self.right_gesture_pub.publish(String(data=right_gesture))
        self.waypoint_pub.publish(waypoint)


def main(args=None):
    rclpy.init(args=args)

    handcv = HandCV()

    rclpy.spin(handcv)


if __name__ == "__main__":
    main()
